# Generated by Django 5.2 on 2025-05-14 23:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_assignment_created_at_remove_course_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assignment",
            name="description",
        ),
        migrations.RemoveField(
            model_name="assignment",
            name="due_date",
        ),
        migrations.RemoveField(
            model_name="course",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="course",
            name="description",
        ),
        migrations.RemoveField(
            model_name="submission",
            name="submitted_at",
        ),
        migrations.AlterField(
            model_name="assignment",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.course"
            ),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="assignments/"),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="courses/"),
        ),
        migrations.AlterField(
            model_name="course",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="assignment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.assignment"
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="file",
            field=models.FileField(upload_to="submissions/"),
        ),
        migrations.AlterField(
            model_name="submission",
            name="grade",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="submission",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.CreateModel(
            name="EspaceDepot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=200)),
                (
                    "matiere",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="espaces_depot",
                        to="core.course",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="course",
            name="espace_depot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.espacedepot",
            ),
        ),
    ]
