# Generated by Django 5.2 on 2025-05-15 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_assignment_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="espacedepot",
            name="matiere",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="espaces_depot",
                to="core.course",
            ),
        ),
    ]
