# Generated by Django 5.2 on 2025-05-15 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_espacedepot_matiere"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.course",
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="assignment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.assignment",
            ),
        ),
    ]
