# Generated by Django 5.2 on 2025-05-15 03:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_submission_course_alter_submission_assignment"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentDashboardTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time_spent", models.IntegerField(default=0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboard_times",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
